FROM debian

RUN apt update && \
    apt install -y python3 python3-pip openssh-server

RUN mkdir Code

WORKDIR /Code

COPY ./code/requirements.txt .
COPY ./code/shell.py .
COPY ./code/spinningbar.py .
COPY ./code/main.py .
RUN mkdir /var/run/sshd
RUN echo 'root:docker!' | chpasswd

RUN awk '{if($0 ~ /^#?PermitRootLogin/){print "PermitRootLogin yes"}else{print $0}}' /etc/ssh/sshd_config > /tmp/sshd_config_modified && mv /tmp/sshd_config_modified /etc/ssh/sshd_config
RUN python3 -m pip install -r requirements.txt --break-system-packages

COPY ./code/entrypoint.sh .

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]